### ISSUE TITLE
indentation issue?

### ISSUE THREAD

**Issue by Kilian** [blipk/Bowser#1]
Hey, can it be that there is an indentation issue here:

https://github.com/blipk/Bowser/blob/master/bowser.py#L89-L92

With those, `python3 ./bowser.py` never reaches the setup part (with or without `--setup`) on Ubuntu 18.04, netting this error:
```sh
➜  Bowser git:(master) ✗ python3 bowser.py --setup 
[b'24744', b'24745']
[b'24744', b'24747']
Traceback (most recent call last):
  File "bowser.py", line 91, in <module>
    passURI()
  File "bowser.py", line 61, in passURI
    with open(uriFile, 'a+') as file: file.write(bowser.URI+"\r\n"); file.close()
FileNotFoundError: [Errno 2] No such file or directory: '/home/kilian/.config/bowser/.openuri'
```
Commenting line 89 to 92 out installs the app correctly.

**Comment by blipk** [comment]
hey @Kilian 
It's been a while since I touched this, so not sure whats happening.

It's not an indentation issue though, the uri file holds the URL you've opened and the process checks it preiodically as far as I recall, looks like on first run that file isn't there.

I've added a check to skip the check if theres no file to be read, let me know if it works for you with that change.

**Comment by Kilian** [comment]
unfortunately, that hides the error but also does not install

```sh
➜  Bowser git:(master) python bowser.py --setup               
['25691', '25692']
['25691', '25694']
➜  Bowser git:(master) ✗ 

```

**Comment by blipk** [comment]
hi @Kilian can you confirm your python version? and that you have write permission to ~/.config/bowser?

would also be useful to know what distro you are using etc

**Comment by Kilian** [comment]
```sh
➜  ~ python3 --version
Python 3.6.9
```
I'm on Ubuntu 18.04 and I have write permission to the .config folder. In the above, the ~/.config/bowser folder doesn't exist yet. Do I need to make that manually?

**Comment by blipk** [comment]
Hi @Kilian 

You shouldn't have to, the setup() function should lead to saveConfig() which should do that.

Can you check `python --version` as thats how you were running it and may be linking to python2.

Looks like the setup() function isn't completing properly, and I'm not really sure why.

Might be useful to add this after line 127 to see whats happening:
```
print(currentBrowser)
print(installedApps)
```

Can you also let me know what web browsers you have installed and share their .desktop files from the applications directory?

**Comment by blipk** [comment]
Also if you are using Gnome, I might suggest the successor to this instead: https://github.com/blipk/bowser-gnome

**Comment by Kilian** [comment]
It works with neither python3 or python. If I add those print statements after line 127 nothing gets printed, so it seems it's not even reaching there. Indeed, if I add `print("hello")` at line 122, right at the beginning of `setup`, that also doesn't get printed.

```sh
➜  Bowser git:(master) python3 bowser.py --setup
[b'11620', b'11621']
[b'11620', b'11623']
```

Adding print statements at various other points, `bowser.URI` on line fifty is `--setup`, but `if (isRunning(1)):` is true (because it itself is running?) Because `--setup` is neither `--enable` or `--disable`, it passes the URI and exits, and never reaches setup.

I'm using Mate unfortunately, or I would've tried bowser-gnome!

**Comment by Kilian** [comment]
Changing line 94 to 

```python
if (bowser.URI != '--enable' and bowser.URI != '--disable' and bowser.URI != '--setup
```
Installs and launches the application. At that point it registered as the default application but when I `xdg-open` a URL it again goes to `if (isRunning(1)):` and because that returns true, goes to passURI, determines its not a file and...exits the app. 

Only when changing `if (isRunning(1)):` to `if (False and isRunning(1)):` does the app reach `openBrowser` and launch the correct browser.

**Comment by blipk** [comment]
Hey @Kilian 
Thanks for your patience with this, it's been a while since I've touched any of this code, and running things on my end is working fine.

Your entry point should be at line 202:
`if not (path.exists(configFile)): setup(True)`

This should copy all the .py files to ~/.config/bowser as well as create a .conf file there, however you said theres nothing in that directory at all?

I'm not really sure whats happening, but things won't work properly without a config file and without the py files in that directory.

The --setup flag is really to only re-run the initial setup once the config is already there, as URLs and CLI flags get dumped to and read from the .openuri file as a primitive IPC, and this won't happen properly if you havent run the initial set up correctly.

Can you try starting from scratch and just running `python3 bowser.py` without the --setup flag.

If that still doesn't work I'd suggest debugging from line 202 to see whats happening.

**Comment by Kilian** [comment]
With that False in the `if(isRunning(1))` statement, it installed and works correctly. I'd love to get this to work "out of the box".

I still think the (lack of) indentation for the [If statements on line 86](https://github.com/blipk/Bowser/blob/master/bowser.py#L86-L93) is what's causing the issue, because that seems to becomes the first entry point of the application (or sanity check) and the second if statement always returns true because it sees itself, so it does passURI and exits, rather than continuing to line 202 and executing the app as expected. Essentially it short-circuits there.

**Comment by blipk** [comment]
I don't see how its working if you have no config file? You should be presented with a dialog whenever you open a URL to choose which browser to open it with, is that happening?

I'm also not sure what indentation issue you are talking about?

**Comment by Kilian** [comment]
When I change `if (isRunning(1)):` to `if (False and isRunning(1)):` it skips that entire block and _does_ run setup correctly, copying over the files and creating that config file. That means that for me Bowser is now working correctly: it's configured as the default app, it automatically opens the url in the browser I have configured, or shows the dialog whenever I open a new URL. So it's all working as expected. I just had to change that line.

The if clauses on line 86 and line 90 both have no indentation, which means that python reaches those checks and executes them, before it reaches line 202.

**Comment by blipk** [comment]
Ok, confusing as you said before there was nothing in the config folder.

I understand what you mean now, they are not supposed to be indented.
`isRunning(1)` will return True if greater than 1 process is running, and I can see now that on your end that is the case, but on my machine it is not, I only get one PID, so on first setup it should continue down to line 202.

I'm really not sure why you're getting two PIDs back from the pgrep, but that is what the issue is.

Also If you're adding an `if False` there it also means its never going to run passURI(), unless you're removing it after the setup?

I'd suggest again to delete the config folder and re-run without the --setup flag and see if you're still getting two PIDs back, there should really only be one as you're only running it once, perhaps something strange with your python environment or shell or a zombie process from a previous failed run? Might want to kill those too before re-running.

**Comment by blipk** [comment]
If you could try my suggestion and let me know how that goes @Kilian

**Comment by Kilian** [comment]
> I'm really not sure why you're getting two PIDs back from the pgrep, but that is what the issue is.

The `pgrep` command also finds itself. If I print its PID, then it matches the second one:

```python
    print(process.pid)
    print (my_pid.splitlines())
```
Output:
```sh
➜  Bowser git:(master) ✗ python3 bowser.py
7947
[b'7946', b'7947']
7949
[b'7946', b'7949']
```

The first set is the isRunning(2) check, and the second is the isRunning(1) check. For context, I'm running Zsh. Maybe the splitlines can be filtered to exclude the pid of the process, only after which the length is compared?

> Also If you're adding an if False there it also means its never going to run passURI(), unless you're removing it after the setup?

I kept it there and the app works as expected with it.

**Comment by blipk** [comment]
> The pgrep command also finds itself. If I print its PID, then it matches the second one:

Alright, that makes sense now, but doesn't seem to do so on my machine, also using zsh
In any case, I've pushed a change to exclude the pgrep process pid in the count, thanks for digging the cause of that up @Kilian 

> I kept it there and the app works as expected with it.

You might find some issues when passing CLI arguments or opening links from certain places, I'd suggest changing it back, but up to you.

I'd appreciate if you can do a fresh start like I suggested and let me know if the issue is solved.

**Comment by Kilian** [comment]
This solves the issue :heart: Thanks!
