### ISSUE TITLE
command expansion is not performed in KDE

### ISSUE THREAD

**Issue by marco44** [blipk/Bowser#2]
Hi, great project. I've run into a minor issue, because I'm using KDE I suppose.

The command expansion from the .desktop file is not working (`Exec=bash -c "~/.config/bowser/bowser.py \"%u\""`)

From what I understand, this is banned in KDE for security reasons : https://api.kde.org/frameworks/kcoreaddons/html/classKMacroExpanderBase.html#ada9d2fbb7d0b640ba744152b40c24b00 (which in my opinion is a good idea). For me, just removing the bash -c solved it, as bowser.py is executable, but I suppose it's here for good reason

**Comment by blipk** [comment]
Hey @marco44 

It could probably just passed directly instead of a command string, I haven't worked on this in a while so I'm not sure it was necessary for it to be done that way.

This project mostly works as-is though and is in maintenance mode, so I will probably leave it as is for now and keep this as a pinned topic in case anyone else runs into the same issue.

Thanks for the report.
